services:
  db:
    image: postgres:16.4
    environment:
      POSTGRES_DB: mydb
      POSTGRES_USER: xyz
      POSTGRES_PASSWORD: 1
    volumes:
      - postgres_data:/var/lib/postgresql/data
    ports:
      - "5432:5432"

  web:
    build: .
    command: daphne -b 0.0.0.0 -p 8000 config.asgi:application
    volumes:
      - .:/app
    ports:
      - "8000:8000"
    depends_on:
      - db
      - redis

  redis:
    image: redis:6
    ports:
      - "6379:6379"

volumes:
  postgres_data:


